### PR TITLE
Standardising randomisation, small fixes.

### LINKED ISSUE #771: Standardise the randomisation in sorcha.py
See here: https://github.com/dirac-institute/sorcha/blob/1ba036760f54b624c167b8dc05ae8e2f250b9ce6/src/sorcha/sorcha.py#L220

Randomisation is treated differently than all other pipeline operations. The function should, like the others, take in the observations dataframe and return the observations dataframe, with all column manipulations done within the function PPRandomizeMeasurements.

### LINKED ISSUE #773: remove old difi implementation from sorcha
remove old difi implementation from sorcha. It's commented out and not being used currently, but it's time to fully commit to minidifi.

### LINKED ISSUE #774: remove current config file generator utility
remove current config file generator utility

### PR DESCRIPTION
**Pull request by astronomerritt**
Fixes #771.
PPRandomizeMeasurements.randomizeAstrometry now returns a modified dataframe, with all changes to the dataframe being performed inside the function. This brings it in line with other operations in the pipeline. The docstring, relevant demo notebook, and unit test have been updated. While I was in there, I also deleted the lines where numpy functions had been assigned to variables and edited the code to just use the numpy functions instead.

Fixes #774.
Removed the old config file generator and its unit test.

Fixes #773.
Removes the old difi-based implementation of the linking filter. 

## Review Checklist for Source Code Changes

- [ ] Does pip install still work?
- [ ] Have you written a unit test for any new functions?
- [x] Do all the units tests run successfully?
- [x] Does Sorcha run successfully on a test set of input files/databases?
- [x] Have you used black on the files you have updated to confirm python programming style guide enforcement?

### CODE REVIEW

**Review by mschwamb — CHANGES_REQUESTED** [review]
https://github.com/dirac-institute/sorcha/blob/1ba036760f54b624c167b8dc05ae8e2f250b9ce6/pyproject.toml#L41C1-L41C56 
needs removing as well

**Comment by astronomerritt** [comment]
Sorry, don't quite understand. What in pyproject.toml needs to be removed? difi isn't in there, as far as I can tell.

**Comment by mschwamb** [comment]
> Sorry, don't quite understand. What in pyproject.toml needs to be removed? difi isn't in there, as far as I can tell.

It's not difi - it's the config file generator

**Comment by mschwamb** [comment]
makeConfigSorcha = "sorcha.utilities.makeConfigPP:main"

**Comment by astronomerritt** [comment]
Oops. That should be it now.

**Review by mschwamb — APPROVED** [review]
Looks good to me

**Pull request merged**
