### PR TITLE
WIP: Optimize pointings dataframe

### LINKED ISSUE #677: Reduce memory usage
@mjuric will  atempt memory mapping to disk for ephemeris generation output in the main bit of sorcha

### LINKED ISSUE #723: r_obs, v_obs and other vector quantities are being saved as strings

### PR DESCRIPTION
**Pull request by mjuric**
These changes reduce the memory footprint of the pointings dataframe by ~2.8x

Fixes #677 

Fixes #723 

Describe your changes.

## Review Checklist for Source Code Changes

- [ ] Does pip install still work?
- [ ] Have you written a unit test for any new functions?
- [ ] Do all the units tests run successfully?
- [ ] Does Sorcha run successfully on a test set of input files/databases?
- [ ] Have you used black on the files you have updated to confirm python programming style guide enforcement?

### CODE REVIEW

**Comment by mschwamb** [comment]
@astronomerritt is on deck to check the outputs

**Comment by astronomerritt** [comment]
Wait - I'm a little confused. The end-to-end test on this branch is passing (test_demo_end2end.py). That runs Sorcha and the ephemeris generation end-to-end with the demo inputs and a set seed and checks the result against the "goldens", then passes if the outputs are the same.

So we already know the outputs haven't changed, right?

Am I missing something? Was there something else you wanted me to check?

**Comment by mschwamb** [comment]
Is that on Kelvin @astronomerritt ?

**Comment by astronomerritt** [comment]
Yep, that's Kelvin.

**Comment by mschwamb** [comment]
@mjuric  you'll need a rebase before this can be merged

**Review by mschwamb — APPROVED** [review]
approved pending conflicts are sorted by @mjuric

**Pull request merged**
