### PR TITLE
Including code to process a subset of inputs, fixing unit tests

### LINKED ISSUE #982: process a slice of an input file
https://github.com/dirac-institute/sorcha/pull/980/commits/b873cd975b9d70ad1fe021cddfd37116f60cd8e5

### LINKED ISSUE #995: Two unit tests fail if sorcha-addons is installed
Two of Sorcha's unit tests fail if sorcha-addons is installed.

First, in tests/activity/test_activity_registration.py, `test_register_subclasses()` fails with an assertion error. When I print the variables in question: 

```
>> print(output)

{'identity': <class 'sorcha.activity.identity_activity.IdentityCometaryActivity'>, 'lsst_comet': <class 'sorcha_addons.activity.lsst_comet.lsst_comet_activity.LSSTCometActivity'>}

>> print (CA_METHODS)

{'identity': <class 'sorcha.activity.identity_activity.IdentityCometaryActivity'>}
```

Second, in tests/lightcurves/test_lightcurve_registration.py, `test_register_subclasses()` fails similarly.

```
>> print(output)

{'identity': <class 'sorcha.lightcurves.identity_lightcurve.IdentityLightCurve'>, 'sinusoidal': <class 'sorcha_addons.lightcurve.sinusoidal.sinusoidal_lightcurve.SinusoidalLightCurve'>}

>> print (CA_METHODS)

{'identity': <class 'sorcha.lightcurves.identity_lightcurve.IdentityLightCurve'>}
```

Looking at this, I think I can see how desired behaviour is accidentally tripping the unit tests. I'd still like @bernardinelli to look at it please :)

### PR DESCRIPTION
**Pull request by astronomerritt**
Fixes #982.
- There is now an optional command-line option, --process-subset, which allows you to process just a subset of your input orbit/parameters files. By default this is 1/1 (i.e., process everything).
- Usage/example: `--process subset 2/10` will process the second tenth of the objects in the orbit file.
- I integrated Mario's code for this and also fixed it so it works with external ephemeris files.
- Wrote unit tests.

Fixes #995.
- Implemented Drew's fix for the two unit tests which fail when sorcha-addons is installed.

## Review Checklist for Source Code Changes

- [x] Does pip install still work?
- [x] Have you written a unit test for any new functions?
- [x] Do all the units tests run successfully?
- [x] Does Sorcha run successfully on a test set of input files/databases?
- [x] Have you used black on the files you have updated to confirm python programming style guide enforcement?

### CODE REVIEW

**Comment by mschwamb** [comment]
@astronomerritt  can you resolve conflicts?

**Comment by astronomerritt** [comment]
Done here too!

**Comment by mschwamb** [comment]
Some issues https://github.com/dirac-institute/sorcha/issues/1009

**Review by mschwamb — CHANGES_REQUESTED** [review]
There's an issue ticket submitted about the performance of this PR

**Comment by mschwamb** [comment]
At this point, this PR is too far out of date, that I think we should come back to this at a later time with a fresh PR.

**Pull request closed without merging**
