### PR TITLE
Removed deprecated pkg_resources call

### LINKED ISSUE #736: Possibly incorrect sky rotation angle
As discussed here, the rotation of the field of view is reversed from what is done in objectsInField. It's unclear which uses the correct direction. We should check with the operations simulation team which is correct, and verify we use the right reference angle.

### LINKED ISSUE #745: PPFootprintFilter.py depricated call
/Users/mschwamb/Research/python/lsst/survey_simulator/sorcha/sorcha_main_repo/sorcha/src/sorcha/modules/PPFootprintFilter.py:25: DeprecationWarning: pkg_resources is deprecated as an API.[]( See https://setuptools.pypa.io/en/latest/pkg_resources.html)
    import pkg_resources

### PR DESCRIPTION
**Pull request by samncorn**
Fixes # .

Replaced call to pkg_resources with call to importlib_resources. (Fixes #745)

Corrected direction of image rotation angle. (Fixes #736)

## Review Checklist for Source Code Changes

- [ ] Does pip install still work?
- [ ] Have you written a unit test for any new functions?
- [ ] Do all the units tests run successfully?
- [ ] Does Sorcha run successfully on a test set of input files/databases?
- [ ] Have you used black on the files you have updated to confirm python programming style guide enforcement?

### CODE REVIEW

**Comment by mschwamb** [comment]
@sam  The two errors coming up on the CI are because of install requirements. You'll need to also change the requirement.txt file in the docs folder,  adding importlib_resources, You'll also need to  add importlib_resources as an dependency in pyproject.toml

**Comment by mschwamb** [comment]
@samncorn  Looks like you made good progress. Can you assign a reviewer and edit the description to include all the tickets it closes when you're ready for this be reviewed?

**Comment by mschwamb** [comment]
Any reason why this was closed? @Gerenjie was testing this

**Comment by samncorn** [comment]
Whoops. I think it's because I renamed the branch.

**Review by mschwamb — APPROVED** [review]
Approved pending resolving conflicts

**Pull request merged**
