### PR TITLE
Assorted variable renaming for clarity and consistency

### LINKED ISSUE #599: clarify time units
Based on a chat with @matthewholman: Given the whole in email discussion about time and which definition we're using where, we're going to want to clearly enforce what we're defining time as. So everywhere we're going to want to change these two variables: 

observationStartMJD --> observationStartMJD_TAI
FieldMJD --> FieldMJD_TAI

### PR DESCRIPTION
**Pull request by drewoldag**
Fixes #599 #608 #609   .

Renaming `jd_tdb` -> `JD_TDB`.
Renaming `epoch` -> `epochMJD_TDB`.
Renaming  `observationStartMJD` -> `observationStartMJD_TAI`.
Renaming `FieldMJD` -> `FieldMJD_TAI`.

## Review Checklist for Source Code Changes

- [x] Does pip install still work?
- [ ] Have you written a unit test for any new functions?
- [x] Do all the units tests run successfully?
- [x] Does Sorcha run successfully on a test set of input files/databases?
- [x] Have you used black on the files you have updated to confirm python programming style guide enforcement?

### CODE REVIEW

**Comment by drewoldag** [comment]
I expect unit tests for fail after the most recent commit because there is a test data file in HDF5 format that needs to be updated. I don't immediately know how to do that, and I need to head out to pick up kids from school. I'll fix up the test file in my next commit.

**Comment by mschwamb** [comment]
@astronomerritt  could you help @drewoldag  with the hdf5 file?

**Comment by astronomerritt** [comment]
@mschwamb @drewoldag should be able to get it sorted this afternoon!

**Comment by astronomerritt** [comment]
As I am a scrub who does not know how to contribute to an open PR, I have emailed @drewoldag the edited HDF5 file :)

**Comment by drewoldag** [comment]
@astronomerritt thanks for your help with the HDF5 file! Got it all sorted out :)

**Review by maxwest-uw — APPROVED** [review]

**Pull request merged**
