### PR TITLE
WIP: Enable CI on AppleSilicon

### PR DESCRIPTION
**Pull request by mjuric**
Enabling macOS CI on AppleSilicon

Per https://github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions/

Fixes # .

Describe your changes.

## Review Checklist for Source Code Changes

- [ ] Does pip install still work?
- [ ] Have you written a unit test for any new functions?
- [ ] Do all the units tests run successfully?
- [ ] Does Sorcha run successfully on a test set of input files/databases?
- [ ] Have you used black on the files you have updated to confirm python programming style guide enforcement?

### CODE REVIEW

**Comment by mschwamb** [comment]
@mjuric  any news on this?

**Comment by mjuric** [comment]
Still nothing; I pinged GH support again. Let's keep this ticket opened.

**Comment by mschwamb** [comment]
@mjuric  Any news?

**Comment by mjuric** [comment]
image

:(.

**Comment by mschwamb** [comment]
Maybe time for a new ticket?

**Comment by mschwamb** [comment]
@mjuric  Can you poke github on this again or make a new ticket?

**Comment by mschwamb** [comment]
M1 mac runner is now public

**Pull request closed without merging**
