### PR TITLE
Demo lca

### PR DESCRIPTION
**Pull request by bernardinelli**
Adds a demo notebook for the lightcurve methods, and fixes a typo in the apparent magnitude validation notebook

## Review Checklist for Source Code Changes

- [ ] Does pip install still work?
- [ ] Have you written a unit test for any new functions?
- [ ] Do all the units tests run successfully?
- [ ] Does Sorcha run successfully on a test set of input files/databases?
- [x] Have you used black on the files you have updated to confirm python programming style guide enforcement?

### CODE REVIEW

**Comment by mschwamb** [comment]
Should demo light curve go into sorcha addons https://sorcha-addons.readthedocs.io/en/latest/index.html?

**Comment by mschwamb** [comment]
Also this is really well written and informative and does a great job explaining how lc and phase curve effect relate.

**Comment by bernardinelli** [comment]
> Should demo light curve go into sorcha addons https://sorcha-addons.readthedocs.io/en/latest/index.html? I think it might go better in addons.

I can see it going either here, or in the addons repository - I will leave it up to you. This demo shows both how to add a custom lightcurve function (that doesn't depend on anything but "basic" sorcha), and how to use the addons repo, so I have a slight preference for adding it here, with a caveat that I/we should write a bit about sorcha_addons in the introduction of the notebook. What do you think?

**Comment by mschwamb** [comment]
I agree. That sounds good. This is what i was envisioning for sorcha and more. Once you make that change add update on thing in the docs folder, I'll approve. 

 The notebooks are rerun in the github CI. You'll need to add sorcha add-ons to the requirements so it gets pip installed https://github.com/dirac-institute/sorcha/blob/main/docs/requirements.txt

There's also a [very basic notebook in sorcha add-ons ](https://sorcha-addons.readthedocs.io/en/latest/notebooks/lightcurve/sinusoidal/sinusoidal_example.html)to show up off your lc function. If you can next add a bit of text that maybe refers back to this notebook and in that notebook in the add-ons repo plots the light curves produced after this PR is merged. That would be great.

**Comment by mschwamb** [comment]
Oh one more thing- add  the notebook to this as well list https://github.com/dirac-institute/sorcha/blob/main/docs/notebooks.rst

**Review by mschwamb — APPROVED** [review]

**Pull request merged**
